#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 03 16:04:18 CEST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_simple_axi_register_behav -key {Behavioral:simple_axi_register:Functional:tb_simple_axi_register} -tclbatch tb_simple_axi_register.tcl -protoinst "protoinst_files/axi_register_verification.protoinst" -log simulate.log"
xsim tb_simple_axi_register_behav -key {Behavioral:simple_axi_register:Functional:tb_simple_axi_register} -tclbatch tb_simple_axi_register.tcl -protoinst "protoinst_files/axi_register_verification.protoinst" -log simulate.log

